<?php

return [
    'race' => [
        'Aarakocra',
        'Aasimar',
        'Bugbear',
        'Centaur',
        'Changeling',
        'Dragonborn',
        'Dwarf',
        'Elf',
        'Firbolg',
        'Genasi',
        'Gith',
        'Gnome',
        'Goblin',
        'Goliath',
        'Half-Elf',
        'Halfling',
        'Half-Orc',
        'Hobgoblin',
        'Human',
        'Kalashtar',
        'Kenku',
        'Kobold',
        'Lizardfolk',
        'Loxodon',
        'Minotaur',
        'Orc',
        'Shifter',
        'Simic Hybrid',
        'Tabaxi',
        'Tiefling',
        'Tortle',
        'Triton',
        'Vedalken',
        'Viashino',
        'Warforged',
        'Yuan-ti Pureblood',
    ],

    'class' => [
        'Barbarian' => [
            'Path of the Ancestral Guardian',
            'Path of the Battlerager',
            'Path of the Berserker',
            'Path of the Storm Herald',
            'Path of the Totem Warrior',
            'Path of the Zealot',
        ],
        'Bard' => [
            'College of Glamour',
            'College of Lore',
            'College of Swords',
            'College of Valor',
            'College of Whispers',
        ],
        'Cleric' => [
            'Arcana Domain',
            'Death Domain',
            'Forge Domain',
            'Grave Domain',
            'Knowledge Domain',
            'Life Domain',
            'Light Domain',
            'Nature Domain',
            'Order Domain',
            'Tempest Domain',
            'Trickery Domain',
            'War Domain',
        ],
        'Druid' => [
            'Circle of Dreams',
            'Circle of Spores',
            'Circle of the Land',
            'Circle of the Moon',
            'Circle of the Shepherd',
        ],
        'Fighter' => [
            'Arcane Archer',
            'Battle Master',
            'Brute',
            'Cavalier',
            'Champion',
            'Eldritch Knight',
            'Purple Dragon Knight',
            'Samurai',
        ],
        'Monk' => [
            'Way of Shadow',
            'Way of the Drunken Master',
            'Way of the Four Elements',
            'Way of the Kensei',
            'Way of the Long Death',
            'Way of the Open Hand',
            'Way of the Sun Soul',
        ],
        'Paladin' => [
            'Oath of Conquest',
            'Oath of Devotion',
            'Oath of Redemption',
            'Oath of the Ancients',
            'Oath of the Crown',
            'Oath of Vengeance',
            'Oathbreaker',
        ],
        'Ranger' => [
            'Beast Master',
            'Gloom Stalker',
            'Horizon Walker',
            'Hunter',
            'Monster Slayer',
        ],
        'Rogue' => [
            'Arcane Trickster',
            'Assassin',
            'Inquisitive',
            'Mastermind',
            'Scout',
            'Swashbuckler',
            'Thief',
        ],
        'Sorcerer' => [
            'Divine Soul',
            'Draconic Bloodline',
            'Giant Soul',
            'Shadow Magic',
            'Storm Sorcery',
            'Wild Magic',
        ],
        'Warlock' => [
            'The Archfey',
            'The Celestial',
            'The Fiend',
            'The Great Old One',
            'The Hexblade',
            'The Undying',
        ],
        'Wizard' => [
            'School of Abjuration',
            'School of Conjuration',
            'School of Divination',
            'School of Enchantment',
            'School of Evocation',
            'School of Illusion',
            'School of Invention',
            'School of Necromancy',
            'School of Transmutation',
            'War Magic'
        ],
    ],

    'background' => [
        'Acolyte',
        'Anthropologist',
        'Archaeologist',
        'Charlatan',
        'City Watch / Investigator',
        'Clan Crafter',
        'Cloistered Scholar',
        'Courtier',
        'Criminal / Spy',
        'Entertainer',
        'Faction Agent',
        'Far Traveler',
        'Folk Hero',
        'Gladiator',
        'Haunted One',
        'Hermit',
        'House Agent',
        'Inheritor',
        'Knight',
        'Knight of the Order',
        'Mercenary Veteran',
        'Noble',
        'Outlander',
        'Pirate',
        'Sage',
        'Sailor',
        'Soldier',
        'Urban Bounty Hunter',
        'Urchin',
        'Uthgardt Tribe Member',
        'Waterdhavian Noble',
    ],
];